### ISSUE TITLE
[1.7.10]游戏崩溃

### ISSUE THREAD

**Issue by Omgise** [StrangeSmell/NoGuiEvolution#1]
[crash-2024-02-17_19.13.27-server.txt](https://github.com/StrangeSmell/NoGuiEvolution/files/14318562/crash-2024-02-17_19.13.27-server.txt)
[fml-client-latest.log](https://github.com/StrangeSmell/NoGuiEvolution/files/14318563/fml-client-latest.log)

**Comment by StrangeSmell** [comment]
There is a null pointer exception.
Now the latest 1.7.10 version (1.1.3) has been fixed.
Thank you for your submission.

**Comment by Omgise** [comment]
In version 1.1.3, the game crashed while digging for blocks
[crash-2024-02-18_10.29.23-server.txt](https://github.com/StrangeSmell/NoGuiEvolution/files/14320891/crash-2024-02-18_10.29.23-server.txt)
[fml-client-latest.log](https://github.com/StrangeSmell/NoGuiEvolution/files/14320892/fml-client-latest.log)

**Comment by StrangeSmell** [comment]
Sorry, but I cannot reproduce this bug.
Did you appear during the first digging ？

**Comment by StrangeSmell** [comment]
Now the latest 1.7.10 version (1.2.0) has been fixed.(And added forgetting function)
Thank you for your submission.
And I have already tested it.

**Comment by Omgise** [comment]
The game will crash when hitting a creature with a spawn egg

https://github.com/StrangeSmell/NoGuiEvolution/assets/106000018/b45bd29b-98e1-4562-80e7-2bf2ee5928db

[fml-client-latest.log](https://github.com/StrangeSmell/NoGuiEvolution/files/14322854/fml-client-latest.log)

**Comment by StrangeSmell** [comment]
I see......This issue should only exist in 1.7.10 because MC does not record mods data(but in 1.12.2 MC will record). I should write a separate set of logic for 1.7.10.
Thank you for your feedback.
I will upload a new version(1.2.3) soon

**Comment by Omgise** [comment]
It's really fixed, thank you!

**Comment by Omgise** [comment]
New crash
[crash-2024-02-21_10.12.49-client.txt](https://github.com/StrangeSmell/NoGuiEvolution/files/14353246/crash-2024-02-21_10.12.49-client.txt)
[fml-client-latest.log](https://github.com/StrangeSmell/NoGuiEvolution/files/14353248/fml-client-latest.log)

**Comment by StrangeSmell** [comment]
This is because I wanted to collaborate with Thaumcraft, but I forgot to remove it during the build before it could be completed.
I am so sorry....
You can download 1.2.5 .
