### ISSUE TITLE
[1.12.2] Some mobs won't take damage from direct hits or will crash the game if hit by projectiles.

### ISSUE THREAD

**Issue by SonicX8000** [StrangeSmell/NoGuiEvolution#2]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods:
AoA3-3.3.6
HadEnoughItems_1.12.2-4.24.6
NGE-1.12.2-1.2.0-forge

---

I tested out a Diamond Sword on a Zombie and they were able to be killed without any issue... though for Iron Golems... thewy won't take any damage. I later spawned in a bow & arrow and fired an arrow at the same Iron Golem and.... the game crashed.

Crash:
[crash-2024-02-20_01.54.07-server.txt](https://github.com/StrangeSmell/NoGuiEvolution/files/14341130/crash-2024-02-20_01.54.07-server.txt)

I am unsure what other mobs are out there that would run into crashes or would be unable to take damage. I did try some modded weapons like the Advent of Ascension Energy Guns and the game crashed with that upon hitting an Iron Golem with... say the Beamer Energy Gun which fires 3 streams of Projectiles when fired. The Zombie however did take damage without any issue.

Crash:
[crash-2024-02-20_01.59.40-server.txt](https://github.com/StrangeSmell/NoGuiEvolution/files/14341175/crash-2024-02-20_01.59.40-server.txt)

**Comment by SonicX8000** [comment]
It prob would be helpful if I posted what forge & mods were being used, oops.

**Comment by StrangeSmell** [comment]
I see...This is because there is no egg for Iron Golems . I will fix it at 1.2.1 .

**Comment by SonicX8000** [comment]
Some modded mobs that prob spawn without Spawn Eggs, like via a custom way of spawning might also run into this issue, perhaps.

**Comment by StrangeSmell** [comment]
I am so sorry ... This is my first mod , there are so many bugs , although I have fix a lot bugs ...
I have already uploaded the new version (1.2.2)now  . 
Thank you for your issues.
